### ISSUE TITLE
initialize token in conf

### ISSUE THREAD

**Issue by swarmingbee** [waldirio/jira_collect#6]

**Comment by swarmingbee** [comment]
testing out access

**Comment by swarmingbee** [comment]
stack trace from error: 
```
(jira_collect) [shughes@localhost jira_collect{trialrun}]$ ./jira_collect.py 
/home/shughes/git/jira_collect/execution/execution.py:64: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if project_name is "":
Conf file not found! Please, set the token
Traceback (most recent call last):
  File "/home/shughes/git/jira_collect/./jira_collect.py", line 7, in <module>
    from parse import parse
  File "/home/shughes/git/jira_collect/parse/parse.py", line 7, in <module>
    from execution import execution
  File "/home/shughes/git/jira_collect/execution/execution.py", line 11, in <module>
    TOKEN = config.read_token()
  File "/home/shughes/git/jira_collect/config/config.py", line 29, in read_token
    return token_in_file['token']
TypeError: 'NoneType' object is not subscriptable
(jira_collect) [shughes@localhost jira_collect{trialrun}]$ echo "{}" > ~/.jira_collect.conf
```

**Comment by waldirio** [comment]
Hello @swarmingbee 

Fix working as expected. Thank you!!
